# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"somefun": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tomroth.github.io/autograd_simpler/"

git_url = "https://github.com/tomroth/autograd_simpler/tree/master/"

def custom_doc_links(name): return None
