# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['somefun', 'Box']

# Cell
def somefun(x):
    """x is a number, fool"""
    return x**2

# Cell
class Box:
    """A box for values"""
    def __init__(self, x): self.x = x
    def say(self):
        "Apply `somefun` to `x` and print it out"
        return somefun(self.x)
